version: "3"
services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: "db"
      DB_USERNAME: "Oleh"
      DB_PASSWORD: "Oleh_Password"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "school_timetable"
      POSTGRES_USER: "Oleh"
      POSTGRES_PASSWORD: "Oleh_Password"
    ports:
      - "8081:5432"
    volumes:
      - postgre_spring_volume:/var/lib/postgresql/data

volumes:
  postgre_spring_volume:
    driver: local
