export enum EGradeNumber {
  FIRST = "FIRST",
  SECOND = "SECOND",
  THIRD = "THIRD",
  FOURTH = "FOURTH",
  FIFTH = "FIFTH",
  SIXTH = "SIXTH",
  SEVENTH = "SEVENTH",
  EIGHTH = "EIGHTH",
  NINTH = "NINTH",
  TENTH = "TENTH",
  ELEVENTH = "ELEVENTH"
}
