ALTER SEQUENCE class_group_id_seq INCREMENT BY 10;
ALTER SEQUENCE group_limits_id_seq INCREMENT BY 10;
ALTER SEQUENCE lesson_id_seq INCREMENT BY 100;
ALTER SEQUENCE room_id_seq INCREMENT BY 5;
ALTER SEQUENCE subject_id_seq INCREMENT BY 10;
ALTER SEQUENCE teacher_id_seq INCREMENT BY 10;
ALTER SEQUENCE subject_limits_id_seq INCREMENT BY 10;
