# server
server:
  port: 8080

  tomcat:
    threads:
      max: 20
      min-spare: 5

  servlet:
    context-path: '/school-timetable-generator-api'
    session:
      timeout: 2h

# spring
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/school_timetable
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      connection-test-query: SELECT version()

  flyway:
    baseline-on-migrate: true

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_updates: true
#        generate_statistics: true
        format_sql: true
#        show_sql: true

# cors
web:
  cors:
    path-mapping: '/**'
    allowed-origins: 'http://localhost:4200'
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    max-age: 3600


security:
  jwt:
    signing-key: ${SCHOOL_TIMETABLE_GENERATOR_SIGNING_KEY}
    access-token:
      expiration: 14_400_000 # 4 hours
