# server
server:
  port: 8080

  tomcat:
    threads:
      max: 20
      min-spare: 5

  servlet:
    context-path: '/school-timetable-generator-api'
    session:
      timeout: 2h

# spring
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/school_timetable
    username: ${DB_USERNAME:oleh}
    password: ${DB_PASSWORD:qwerty}

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      connection-test-query: SELECT version()

  flyway:
    baseline-on-migrate: true

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_updates: true
#        generate_statistics: true
        format_sql: true
#        show_sql: true

# cors
web:
  cors:
    path-mapping: '/**'
    allowed-origins: 'http://localhost:4200'
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    max-age: 3600


security:
  jwt:
    signing-key: ${SCHOOL_TIMETABLE_GENERATOR_SIGNING_KEY:232808AB4D625165F4F8571D2A7133343147397A14832848298A409E63526255}
    access-token:
      expiration: 14_400_000 # 4 hours

algorithm:
  fitness-function:
    sameSubjectsPerDayLimit: 2
    sameSubjectPerDayFine: 1
#    todo: 05/10/24 there should be exception. e.g: labor work or physical culture teacher
#     could have 2 subgroups from different groups at one lesson
    teacherMaxLessonsAtSameTimeLimit: 1
    teacherMaxLessonsAtSameTimeFine: 1
    roomMaxLessonsAtSameTimeFine: 1