# server
server:
  port: 8080

  tomcat:
    threads:
      max: 20
      min-spare: 5

  servlet:
    context-path: '/school-timetable-generator-api'
    session:
      timeout: 2h

# spring
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_timetable
    username: oleh
    password: qwerty
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      connection-test-query: SELECT version()

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# cors
web:
  cors:
    path-mapping: '/**'
    allowed-origins: 'http://localhost:4200'
    allowed-methods: GET, POST, PUT, DELETE
    max-age: 3600
